### ISSUE TITLE
General To-Do list

### ISSUE THREAD

**Issue by differentsmoke** [Code-for-Miami/queen-tide#4]
- [ ] Incorporate the NOAA data scraping tool to the project. https://github.com/bkerley/tides_and_currents
- [ ] Enable ES6+ JavaScript features. 
- [ ] Replace "king-tide" on the CFM Heroku, either create a new instance or push queen-tide to the king-tide one.
